# Wersja Docker Compose
version: '3'

# Uslugi
services:
  # Reverse-proxy
  reverse-proxy:
    # Obraz TRAEFIK wersja: 2.9
    image: traefik:v2.9
    # Nazwa kontenera
    container_name: reverse-proxy
    # Uruchomienie interfejsu UI oraz wykrywanie
    command: --api.insecure=true --providers.docker
    
    # Porty
    ports:
      # Port HTTP
      - "80:80"
      # Interfejs WEBowy TRAEFIKa (uruchamiany przez --api.insecure=true)
      - "8080:8080"
    
    # Wolumeny
    volumes:
      # Umozliwia Traefikowi nadzorownie instancji dockera
      - "/var/run/docker.sock:/var/run/docker.sock"

  # Jupyter Hub
  hub:
    # Przekierowanie do Dockerfile Jupyter Hub
    build: jupyterhub
    # Nazwa kontenera
    container_name: jupyterhub
    
    # Wolumeny
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "jupyterhub-data:/data"
    - "./jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py"
    
    # Zmienne środowiskowe
    environment:
      # Nazwa uzytkownika z uprawnieniami administratora
      - JUPYTERHUB_ADMIN=admin
      # Nazwa obrazu notatnika Jupyter
      - DOCKER_NOTEBOOK_IMAGE=jupyterlab_img
      # Sciezka do plikow w notatniku
      - DOCKER_NOTEBOOK_DIR=/home/prz
      # Komenda uruchamiajaca notatnik
      - DOCKER_SPAWN_CMD=start-singleuser.sh
      # Nazwa sieci w ktorej beda uruchamiane kontenery
      - DOCKER_NETWORK_NAME=${COMPOSE_PROJECT_NAME}_default

    # Uruchmienie pliku konfiguracyjnego Jupyter Hub
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py
   
    # Etykiety kontenera
    labels:
      # Przekierowanie przez Traefik do kontenera, korzystajac z hosta: localhost (HTTP!)
      - "traefik.http.routers.jupyterhub.rule=Host(`localhost`)"

  # Notatnik Jupyter Lab
  jupyterlab:
    build: jupyterlab
    container_name: jupyter-notebook
    network_mode: none
    command: echo
volumes:
  jupyterhub-data: