# Docker-compose file
# Date: 15.03.2023 DMY

# Docker-compose version
version: '3.9'

services:
  reverse-proxy:
    # Treaefik version: 2.9
    image: traefik:v2.9
    container_name: reverse-proxy
    # Run UI interface and turn on docker detection
    command: --api.insecure=true --providers.docker
    ports:
      # HTTP
      - "80:80"
      # Traefik UI (run by --api.insecure=true)
      - "8080:8080"
    volumes:
      # Allow Traefik to detect docker containers
      - "/var/run/docker.sock:/var/run/docker.sock"

  jupyterhub:
    build: jupyterhub
    container_name: jupyterhub
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:rw"
    - "jupyterhub-data:/data"
    - "./jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
    environment:
      # Jupyterlab container image
      - DOCKER_NOTEBOOK_IMAGE=jupyterlab_img
      # Docker network name
      - DOCKER_NETWORK_NAME=${COMPOSE_PROJECT_NAME}_default
      - HOST=localhost
    # Run Jupyterhub config file
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py
    labels:
      - "traefik.http.routers.jupyterhub.rule=Host(`localhost`)"

  # Notatnik Jupyter Lab
  jupyterlab:
    build: jupyterlab
    image: jupyterlab_img
    container_name: jupyterlab-throaway
    network_mode: none
    command: echo
volumes:
  jupyterhub-data: