entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

api:
  dashboard: false
  insecure: false

providers:
  file:
    filename: /etc/traefik/tls.yml
  docker:
    endpoint: "unix:///var/run/docker.sock"